### ISSUE TITLE
[DOXIA-431] Doxia creates illegal URLs from local paths

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#416]
**[Aaron Digulla](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=digulla)** opened **[DOXIA-431](https://issues.apache.org/jira/browse/DOXIA-431?redirect=false)** and commented

If a local resource contains characters which are illegal in a URL, Doxia creates illegal code or crashes.

---

**Affects:** 1.2

**Comment by jira-importer** [comment]
**[Aaron Digulla](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=digulla)** commented

In an external project, there are image files which contain spaces. Instead of replacing the spaces with %20 or calling `java.net.URLEncoder.encode()`, Doxia tries to call `new java.net.URL("images/The ExTeX Project.png"` which fails.

I tried a fix but couldn't get it to work in a couple of hours. The problem is that you use a lot of Strings when you should be using URLs (or at least a URL-like type). Without such a type, it's impossible to know when a URL must be encoded/decoded.

Example stacktrace:

```
Caused by: java.lang.IllegalArgumentException
        at java.net.URI.create(URI.java:842)
        at org.apache.maven.doxia.site.decoration.inheritance.URIPathDescriptor.<init>(URIPathDescriptor.java:69)
        at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.rebaseLink(DefaultDecorationModelInheritanceAssembler.java:361)
        at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.rebaseBannerPaths(DefaultDecorationModelInheritanceAssembler.java:162)
        at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.assembleModelInheritance(DefaultDecorationModelInheritanceAssembler.java:61)
        at org.apache.maven.doxia.tools.DefaultSiteTool.getDecorationModel(DefaultSiteTool.java:1221)
        at org.apache.maven.doxia.tools.DefaultSiteTool.getDecorationModel(DefaultSiteTool.java:458)
        at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.createSiteRenderingContext(AbstractSiteRenderingMojo.java:285)
        at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:140)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:124)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:107)
        ... 20 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 10: images/The ExTeX Project.png
        at java.net.URI$Parser.fail(URI.java:2809)
        at java.net.URI$Parser.checkChars(URI.java:2982)
        at java.net.URI$Parser.parseHierarchical(URI.java:3066)
        at java.net.URI$Parser.parse(URI.java:3024)
        at java.net.URI.<init>(URI.java:578)
        at java.net.URI.create(URI.java:840)
        ... 30 more
```

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

Can you be more specific: where does this image come from, from an apt/xdoc source file or site.xml? Doxia 1.2 is not used yet in any site release so I assume you are using a snapshot? Is this a regression then? Is it documented somewhere that image/file references may contain spaces (just for my education, I don't think eg that the apt reference is sufficiently precise in many respects)?
