### ISSUE TITLE
[DOXIA-453] ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#434]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** opened **[DOXIA-453](https://issues.apache.org/jira/browse/DOXIA-453?redirect=false)** and commented

If you checkout the tag for version 1.7 of the maven antrun plugin, and run

mvn site site:stage-deploy -Preporting

you will be rewarded with the below. Oddly, when I ran it a second time with -X it went away.

```
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] 1
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.maven.doxia.module.apt.AptParser$Table.traverseRow(AptParser.java:2618)
	at org.apache.maven.doxia.module.apt.AptParser$Table.traverse(AptParser.java:2433)
	at org.apache.maven.doxia.module.apt.AptParser.traverseSectionBlocks(AptParser.java:861)
	at org.apache.maven.doxia.module.apt.AptParser.traverseSection(AptParser.java:807)
	at org.apache.maven.doxia.module.apt.AptParser.traverseSection(AptParser.java:816)
	at org.apache.maven.doxia.module.apt.AptParser.traverseBody(AptParser.java:758)
	at org.apache.maven.doxia.module.apt.AptParser.parse(AptParser.java:228)
	at org.apache.maven.doxia.DefaultDoxia.parse(DefaultDoxia.java:63)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:399)
	at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:53)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:317)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
```

---

**Affects:** 1.2

**Attachments:**
- [DOXIA-453.patch](https://issues.apache.org/jira/secure/attachment/12715437/DOXIA-453.patch) (_1.13 kB_)

**Issue Links:**
- [DOXIA-477](https://issues.apache.org/jira/browse/DOXIA-477) Table justification changes forcing unnecessary work on plain tables

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

One possible fix.

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

In the Apt parser, the justification parser can disagree with the main table parser.

the file that provokes this is usage.apt.vm from the antrun plugin.

I attached a possible fix, but someone might prefer to fix the source of the inconsistency instead.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

```
*-----------------------------------+-----------------------------------+
| <<Ant Expression>>                | <<Maven Expression>>              |
*-----------------------------------------------------------------------+
| Built-in Tasks                                                        |
*-----------------------------------+-----------------------------------+
```

This is causing at least a AIOOBE: an unbalanced table.
Doxia doesn't support colspans. For a colspan for the whole row I can think of a fix, but partial colspans are impossible with the current markup.
Not sure if we should accept colspans.
