### ISSUE TITLE
[DOXIA-68] Adding twiki plugin as build extension makes goal site:site fail.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#523]
**[Martin Zeltner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=swisswheel)** opened **[DOXIA-68](https://issues.apache.org/jira/browse/DOXIA-68?redirect=false)** and commented

When I add the twiki module as an extension in my pom.xml the goal site:site will fail.

Extension config snippet:

---

    <build>
        <extensions>
            
            <extension>
                <artifactId>doxia-module-twiki</artifactId>
                <groupId>org.apache.maven.doxia</groupId>
                <version>1.0-alpha-9-SNAPSHOT</version>
            </extension>
        </extensions>
    </build>

---

Console output:

---

mvn site:site -X
+ Error stacktraces are turned on.
  Maven version: 2.1-SNAPSHOT
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'site'.
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building EL4J module core
  [INFO]    task-segment: [site:site]
  [INFO] ----------------------------------------------------------------------------
  [INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
  [INFO] Setting property: velocimacro.messages.on => 'false'.
  [INFO] Setting property: resource.loader => 'classpath'.
  [INFO] Setting property: resource.manager.logwhenfound => 'false'.
  [INFO] **************************************************************
  [INFO] Starting Jakarta Velocity v1.4
  [INFO] RuntimeInstance initializing.
  [INFO] Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties
  [INFO] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
  [INFO] Resource Loader Instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
  [INFO] ClasspathResourceLoader : initialization starting.
  [INFO] ClasspathResourceLoader : initialization complete.
  [INFO] ResourceCache : initialized. (class org.apache.velocity.runtime.resource.ResourceCacheImpl)
  [INFO] Default ResourceManager initialization complete.
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Include
  [INFO] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
  [INFO] Created: 20 parsers.
  [INFO] Velocimacro : initialization starting.
  [INFO] Velocimacro : adding VMs from VM library template : VM_global_library.vm
  [ERROR] ResourceManager : unable to find resource 'VM_global_library.vm' in any resource loader.
  [INFO] Velocimacro : error using  VM library template VM_global_library.vm : org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'VM_global_library.vm'
  [INFO] Velocimacro :  VM library template macro registration complete.
  [INFO] Velocimacro : allowInline = true : VMs can be defined inline in templates
  [INFO] Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT replace previous VM definitions
  [INFO] Velocimacro : allowInlineLocal = false : VMs defined inline will be  global in scope if allowed.
  [INFO] Velocimacro : initialization complete.
  [INFO] Velocity successfully started.
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Error getting reports from the plugin 'org.apache.maven.plugins:maven-jxr-plugin': Unable to find the mojo 'org.apache.maven.plugins:maven-jxr-plugin:2.1-SNAPSHOT:jxr' in the plugin 'org.apache
  .maven.plugins:maven-jxr-plugin'
  [INFO] ------------------------------------------------------------------------
  [DEBUG] Trace
  org.apache.maven.lifecycle.LifecycleExecutionException: Error getting reports from the plugin 'org.apache.maven.plugins:maven-jxr-plugin': Unable to find the mojo 'org.apache.maven.plugins:maven-jxr-p
  lugin:2.1-SNAPSHOT:jxr' in the plugin 'org.apache.maven.plugins:maven-jxr-plugin'
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:689)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:637)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:512)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:393)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:182)
  at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:690)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:380)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:585)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
  Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-jxr-plugin:2.1-SNAPSHOT:jxr' in the plugin 'org.apache.maven.plugins:maven-jxr-plugin
  '
  at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:538)
  at org.apache.maven.plugin.DefaultPluginManager.getReport(DefaultPluginManager.java:467)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:678)
  ... 19 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-jxr-plugin:2.1-SNAPSHOT:j
  xr', it could not be started
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:339)
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
  at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:529)
  ... 21 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:109)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
  at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
  ... 23 more
  Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:33)
  at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
  ... 26 more
  Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed of field siteRenderer in object of type org.apache.maven.plugin.jxr.JxrReport because the requirement Comp
  onentRequirement{role='org.apache.maven.doxia.siterenderer.Renderer', roleHint='null', fieldName='siteRenderer'} was missing
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:154)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.java:73)
  at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:68)
  at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
  ... 28 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.doxia.siterenderer.Renderer', it could not be started
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:339)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:129)
  ... 32 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:109)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
  at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:92)
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
  ... 33 more
  Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:33)
  at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
  ... 36 more
  Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed for the field siteModuleManager in object of type org.apache.maven.doxia.siterenderer.DefaultSiteRenderer
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:144)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.java:73)
  at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:68)
  at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
  ... 38 more
  Caused by: java.lang.IllegalArgumentException
  at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:63)
  at java.lang.reflect.Field.set(Field.java:656)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:137)
  ... 42 more
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: 3 seconds
  [INFO] Finished at: Mon Aug 14 16:02:55 CEST 2006
  [INFO] Final Memory: 7M/13M
  [INFO] ------------------------------------------------------------------------
  FATAL ERROR: Unable to configure the Maven application
  Error stacktrace:
  org.apache.maven.reactor.MavenExecutionException: Error getting reports from the plugin 'org.apache.maven.plugins:maven-jxr-plugin': Unable to find the mojo 'org.apache.maven.plugins:maven-jxr-plugin:
  2.1-SNAPSHOT:jxr' in the plugin 'org.apache.maven.plugins:maven-jxr-plugin'
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:194)
  at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:690)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:380)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:585)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
  Caused by: org.apache.maven.lifecycle.LifecycleExecutionException: Error getting reports from the plugin 'org.apache.maven.plugins:maven-jxr-plugin': Unable to find the mojo 'org.apache.maven.plugins:
  maven-jxr-plugin:2.1-SNAPSHOT:jxr' in the plugin 'org.apache.maven.plugins:maven-jxr-plugin'
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:689)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:637)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:512)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:393)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:182)
  ... 10 more
  Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-jxr-plugin:2.1-SNAPSHOT:jxr' in the plugin 'org.apache.maven.plugins:maven-jxr-plugin
  '
  at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:538)
  at org.apache.maven.plugin.DefaultPluginManager.getReport(DefaultPluginManager.java:467)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getReports(DefaultLifecycleExecutor.java:678)
  ... 19 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-jxr-plugin:2.1-SNAPSHOT:j
  xr', it could not be started
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:339)
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
  at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:529)
  ... 21 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:109)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
  at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
  ... 23 more
  Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:33)
  at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
  ... 26 more
  Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed of field siteRenderer in object of type org.apache.maven.plugin.jxr.JxrReport because the requirement Comp
  onentRequirement{role='org.apache.maven.doxia.siterenderer.Renderer', roleHint='null', fieldName='siteRenderer'} was missing
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:154)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.java:73)
  at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:68)
  at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
  ... 28 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.doxia.siterenderer.Renderer', it could not be started
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:339)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:129)
  ... 32 more
  Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:109)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
  at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:92)
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
  ... 33 more
  Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:33)
  at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
  ... 36 more
  Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed for the field siteModuleManager in object of type org.apache.maven.doxia.siterenderer.DefaultSiteRenderer
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:144)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.java:73)
  at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:68)
  at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
  ... 38 more
  Caused by: java.lang.IllegalArgumentException
  at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:63)
  at java.lang.reflect.Field.set(Field.java:656)
  at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:137)
  ... 42 more

---

When I copy the twiki package with all java classes in module "doxia-core" (java code remains in same package) the site goal works well and translates the twiki pages as well. It seams that the plexus container has a problem when plexus components are defined in multiple jars. Could this be a Java5 problem? A security manager problem (as you can see the leaf exception is a "UnsafeObjectFieldAccessorImpl")? Comments are welcome!

Cheers,
Martin

---

**Affects:** 1.0-alpha-8

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

I haven't used the twiki module myself, so I can tell you which features it has.
But this issue is about how you configure it so it works. By the look of Dave's comment he seemed to have solved how to do it...

**Comment by jira-importer** [comment]
**[Petr Kozelka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pkozelka)** commented

I wonder if there is a way to make twiki working against released versions. I tried this:

```
...
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-project-info-reports-plugin</artifactId>
        <version>2.1.2</version>
        <dependencies>
          <dependency>
            <groupId>org.apache.maven.doxia</groupId>
            <artifactId>doxia-module-twiki</artifactId>
            <version>1.1.2</version>
          </dependency>
        </dependencies>
      </plugin>
...
```

but got following error:

```
...
this realm = plexus.core
urls[0] = file:/home/pk/opt/maven/lib/maven-2.2.1-uber.jar
Number of imports: 10
import: org.codehaus.classworlds.Entry@a6c57a42
import: org.codehaus.classworlds.Entry@12f43f3b
import: org.codehaus.classworlds.Entry@20025374
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@92758522
import: org.codehaus.classworlds.Entry@ebf2705b
import: org.codehaus.classworlds.Entry@bb25e54
import: org.codehaus.classworlds.Entry@bece5185
import: org.codehaus.classworlds.Entry@3fee8e37
import: org.codehaus.classworlds.Entry@3fee19d8
-----------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error getting reports from the plugin 'org.apache.maven.plugins:maven-project-info-reports-plugin:2.1.2': Unable to find the mojo 'project-team' (or one of its required components) in the plugin 'org.apache.maven.plugins:maven-project-info-reports-plugin'
org.apache.maven.doxia.module.site.AbstractSiteModule.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
...
```

It seems that adding the dependency impacts dependency graph for the plugin classpath somehow. Is there any better version to use ?

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

Doxia 1.1.x is not compatible with any (yet) published site/project-info plugin. Try the newest twiki module from the 1.0.x branch, it should work as per comments above.
