### ISSUE TITLE
[DOXIA-492] Add support for doxia macros in markdown documents.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#587]
**[Juergen Kellerer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=juergenk)** opened **[DOXIA-492](https://issues.apache.org/jira/browse/DOXIA-492?redirect=false)** and commented

It would be nice if doxia macros could be supported also inside markdown documents (similar to APT).

Existing macros (especially snippet) is very useful, however with the power of maven there's the ability to register own macros for a build process which enables reuse of resources and improves dryness in general.

A syntax which may work could be the following:

* Block Level

```
#`??MACRO_NAME MACRO_ARGS`
```

* Inline

```
`??MACRO_NAME MACRO_ARGS`
```

Reference: http://hackage.haskell.org/packages/archive/yesod-markdown/0.0/doc/html/Yesod-Markdown-Macros.html

E.g. using "Texts" it works just from the Editor:

!screen.png!

When macros are not interpreted, they fallback to a code block, thus it's easy to edit these sort of documents with one of the existing nice markdown editors.

---

**Affects:** 1.4

**Attachments:**
- [maven-site-plugin-integration-test.patch](https://issues.apache.org/jira/secure/attachment/12773893/maven-site-plugin-integration-test.patch) (_947 bytes_)
- [screen.png](https://issues.apache.org/jira/secure/attachment/12715632/screen.png) (_38.96 kB_)

**Issue Links:**
- [DOXIA-559](https://issues.apache.org/jira/browse/DOXIA-559) Doxia macro fails with markdown headers past level 4

- [DOXIA-529](https://issues.apache.org/jira/browse/DOXIA-529) Add macro support to XHTML
 (_**"depends upon"**_)

6 votes, 11 watchers

**Comment by jira-importer** [comment]
**[Santiago M. Mola](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=smolav)** commented

This is a must for me. Fortunately, there is a workaround using velocity macros: http://verhas.github.io/mdsnippet/

**Comment by jira-importer** [comment]
**[Jose A. Iñigo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=codependent)** commented

Thank's for the suggestion. Unfortunately there are other macros not covered by that workaround:
Echo Macro
TOC Macro
SWF Macro

**Comment by jira-importer** [comment]
**[Daniel Wegener](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dwegener)** commented

This really is a must...

**Comment by jira-importer** [comment]
**[Masatake Iwasaki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims)** commented

[Daniel Wegener](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dwegener), I think you will be able to use macro after 1.7 to which DOXIA-529 already came in, by using HTML comment in Markdown as

```
<!-- MACRO{toc|fromDepth=0|toDepth=3} -->
```

**Comment by jira-importer** [comment]
**[Daniel Wegener](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dwegener)** commented

Sounds great! I dont want to push or something, but would you have any estimates about and when and how?
I'am using (uhm - standard case?) doxia do render a maven site. Would it be sufficient to add the doxia-xhtml-module-1.7 as dependency to the maven-site-plugin?

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

1. I'm working on the release, but it takes time since I have a lot of cleanup to do at misc levels
2. Masatake is right: it should work, but I didn't test and I'm not sure anybody tested that HTML macros work in Markdown

then can someone build 1.7-SNAPSHOT for himself and check that HTML macro works in Markdown (upgrading dependency in m-site-p), please?
This would let me more time to work on cleanup towards the release

**Comment by jira-importer** [comment]
**[Andreas Veithen-Knowles](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=veithen)** commented

I tried this, but got the following exception:

```
java.lang.NullPointerException
	at org.apache.maven.doxia.parser.AbstractParser.executeMacro(AbstractParser.java:116)
	at org.apache.maven.doxia.module.xhtml.XhtmlParser.processMacro(XhtmlParser.java:269)
	at org.apache.maven.doxia.module.xhtml.XhtmlParser.handleComment(XhtmlParser.java:234)
	at org.apache.maven.doxia.parser.AbstractXmlParser.parseXml(AbstractXmlParser.java:263)
	at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:145)
	at org.apache.maven.doxia.parser.XhtmlBaseParser.parse(XhtmlBaseParser.java:96)
	at org.apache.maven.doxia.module.xhtml.XhtmlParser.parse(XhtmlParser.java:357)
	at org.apache.maven.doxia.module.markdown.MarkdownParser.parse(MarkdownParser.java:109)
	at org.apache.maven.doxia.DefaultDoxia.parse(DefaultDoxia.java:65)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:411)
	at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:51)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:324)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:132)
	at org.apache.maven.plugins.site.render.SiteMojo.renderDoxiaDocuments(SiteMojo.java:262)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:172)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

Looks like a problem with the injection of MacroManager.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

ok, stupid me who don't use Plexus where necessary.
fixed in [r1715602](http://svn.apache.org/r1715602), can you try once more, please?
(if you could write a unit test, that would be absolutely wonderful)

**Comment by jira-importer** [comment]
**[Andreas Veithen-Knowles](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=veithen)** commented

Your change sets secondParsing=true, but then macros are not executed. With secondParsing=false I get the expected result.

**Comment by jira-importer** [comment]
**[Masatake Iwasaki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iwasakims)** commented

As [Andreas Veithen-Knowles](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=veithen) pointed out, secondParsing=false (or just commenting out the line of `setSecondParsing( true );`) worked for me too.
