### ISSUE TITLE
[DOXIA-496] AptParser cannot render velocimacros file with literal anchors in links

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#590]
**[Brandon Heck](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brandon.heck)** opened **[DOXIA-496](https://issues.apache.org/jira/browse/DOXIA-496?redirect=false)** and commented

When generating a site, I get the following error and a subsequent build failure:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project <myProject>: Error during page generation: Error parsing '<theFile>.apt.vm': line [15] missing '}' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project <myProject>: Error during page generation
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:318)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:592)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during page generation
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error parsing '<myFile>.apt.vm': line [15] missing '}'
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:414)
	at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:53)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	... 21 more
Caused by: org.apache.maven.doxia.module.apt.AptParseException: missing '}'
	at org.apache.maven.doxia.module.apt.AptParser.parse(AptParser.java:235)
	at org.apache.maven.doxia.DefaultDoxia.parse(DefaultDoxia.java:65)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:406)
	... 26 more
Caused by: org.apache.maven.doxia.module.apt.AptParseException: missing '}'
	at org.apache.maven.doxia.module.apt.AptParser.skipTraversedLinkAnchor(AptParser.java:1485)
	at org.apache.maven.doxia.module.apt.AptParser.doTraverseText(AptParser.java:453)
	at org.apache.maven.doxia.module.apt.AptParser$Block.traverseText(AptParser.java:1788)
	at org.apache.maven.doxia.module.apt.AptParser$Block.traverseText(AptParser.java:1775)
	at org.apache.maven.doxia.module.apt.AptParser$Paragraph.traverse(AptParser.java:2209)
	at org.apache.maven.doxia.module.apt.AptParser.traverseSectionBlocks(AptParser.java:868)
	at org.apache.maven.doxia.module.apt.AptParser.traverseSection(AptParser.java:814)
	at org.apache.maven.doxia.module.apt.AptParser.traverseBody(AptParser.java:765)
	at org.apache.maven.doxia.module.apt.AptParser.parse(AptParser.java:230)
	... 28 more
```

This appears to be related to parsing a literal anchor in an apt velocimacros file, similar to the following:

```
`{./apidocs/org/brandon/example/MyClass.html##broken(java.lang.String)}broken`
```

This happens whether the link (or the entire file) contains any velocimacro references or not.

Sorry if this is the wrong place to log this, the Velocity page has no issue tracking defined [1].

[1] - http://velocity.apache.org/issue-tracking.html

---

**Affects:** 1.4

1 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Jared Roberts](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jlr787s)** commented

I found a workaround to this issue that isn't pretty, but functions.

```
#set( $method1 = '##broken(java.lang.String)' )
`{./apidocs/org/brandon/example/MyClass.html$method1}broken`
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Interesting catch, but I can explain it:
The template is now first parsed by velocity, then it'll go through the APT parser.
Since `##` is considered as the start of a comment, everything after it is ignored, causing the APT parser to fail.
Have you tried escaping the hashtag(s)?

**Comment by jira-importer** [comment]
**[Jared Roberts](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jlr787s)** commented

Yes, I tried all combinations of escaping both hashtags and one or the other. It either caused the error above or the problem that was worked around by DOXIA-397 -- which is the reason for needing the double hash.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Everything works fine with 1.7 when `$esc.h` is used.
