### ISSUE TITLE
[DOXIA-523] Ampersands after hash in markdown link syntax are now throwing parse errors.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#604]
**[Dan Dumont](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ddumont)** opened **[DOXIA-523](https://issues.apache.org/jira/browse/DOXIA-523?redirect=false)** and commented

This used to work with doxia 1.3, broke in 1.4 and is still a problem.

---

**Affects:** 1.4, 1.5, 1.6

**Attachments:**
- [example.zip](https://issues.apache.org/jira/secure/attachment/12715647/example.zip) (_1.31 kB_)

**Issue Links:**
- [DOXIA-554](https://issues.apache.org/jira/browse/DOXIA-554) Parsing Markdown documents can hang site generation: switch parser from Pegdown to Flexmark

- [DOXIA-436](https://issues.apache.org/jira/browse/DOXIA-436) Remove xhtml-module dependency of markdown module
 (_**"depends upon"**_)

0 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Dan Dumont](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ddumont)** commented

According to http://tools.ietf.org/html/rfc3986#section-3.5 the '&' char is a valid char for the fragment.  It is not reasonable to expect to have to convert all of our markdown to pre-encode this.

**Comment by jira-importer** [comment]
**[Petar Tahchiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paranoiabla)** commented

Looking at the root cause of the exception in the stack trace I think it's more an issue in `plexus-utils`:

```
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: entity reference name can not contain character =' (position: START_TAG seen ...<a href="http://www.example.com?query#obj=foo&id=... @1:77) 
	at org.codehaus.plexus.util.xml.pull.MXParser.parseEntityRef(MXParser.java:2277)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseAttribute(MXParser.java:2085)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseStartTag(MXParser.java:1837)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1297)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextToken(MXParser.java:1138)
	at org.apache.maven.doxia.parser.AbstractXmlParser.parseXml(AbstractXmlParser.java:289)
	at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:145)
	... 31 more

```
