### ISSUE TITLE
[DOXIA-559] Doxia macro fails with markdown headers past level 4

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#631]
**[Alex O'Ree](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=spyhunter99)** opened **[DOXIA-559](https://issues.apache.org/jira/browse/DOXIA-559?redirect=false)** and commented

attempting to include the TOC using a markdown file. If you have any headers past level 3, the TOC fails

using maven site plugin version 3.6, which looks like it's using doxia 1.7.4a
I c&p'd http://svn.apache.org/viewvc/maven/doxia/doxia/trunk/doxia-modules/doxia-module-markdown/src/test/resources/macro-toc.md?view=markup&pathrev=1716285#l2
however no TOC is outputted on a test.md.vm file.
If I change the file name to test.md (dropping the vm extension), I get a stack dump. "EmtpyStackException" when rendering this file. Not sure what I'm doing wrong

```
Caused by: java.util.EmptyStackException
        at java.util.Stack.peek(Unknown Source)
        at org.apache.maven.doxia.index.IndexingSink.peek(IndexingSink.java:292)
        at org.apache.maven.doxia.index.IndexingSink.text(IndexingSink.java:239)
        at org.apache.maven.doxia.sink.impl.SinkAdapter.text(SinkAdapter.java:874)
        at org.apache.maven.doxia.parser.XhtmlBaseParser.handleText(XhtmlBaseParser.java:783)
        at org.apache.maven.doxia.parser.AbstractXmlParser.parseXml(AbstractXmlParser.java:254)
        at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:145)
        at org.apache.maven.doxia.parser.XhtmlBaseParser.parse(XhtmlBaseParser.java:96)
        at org.apache.maven.doxia.module.xhtml.XhtmlParser.parse(XhtmlParser.java:356)
        at org.apache.maven.doxia.macro.toc.TocMacro.execute(TocMacro.java:117)
        at org.apache.maven.doxia.parser.AbstractParser.executeMacro(AbstractParser.java:136)
        at org.apache.maven.doxia.module.xhtml.XhtmlParser.processMacro(XhtmlParser.java:268)
        at org.apache.maven.doxia.module.xhtml.XhtmlParser.handleComment(XhtmlParser.java:233)
        at org.apache.maven.doxia.parser.AbstractXmlParser.parseXml(AbstractXmlParser.java:263)
        at org.apache.maven.doxia.parser.AbstractXmlParser.parse(AbstractXmlParser.java:145)
        at org.apache.maven.doxia.parser.XhtmlBaseParser.parse(XhtmlBaseParser.java:96)
        at org.apache.maven.doxia.module.xhtml.XhtmlParser.parse(XhtmlParser.java:356)
        at org.apache.maven.doxia.module.markdown.MarkdownParser.parse(MarkdownParser.java:112
        at org.apache.maven.doxia.DefaultDoxia.parse(DefaultDoxia.java:65)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:449)
        at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:53)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:337)
        at org.apache.maven.plugins.site.render.SiteMojo.renderDoxiaDocuments(SiteMojo.java:262)
        at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:168)
        at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:132)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

---

**Affects:** 1.7

**Attachments:**
- [toc-macro-test.md](https://issues.apache.org/jira/secure/attachment/12885975/toc-macro-test.md) (_1.22 kB_)

**Issue Links:**
- [DOXIA-533](https://issues.apache.org/jira/browse/DOXIA-533) \<h4>title\</h4> in xdoc source cause wrong output (and make toc macro fail)

- [DOXIA-492](https://issues.apache.org/jira/browse/DOXIA-492) Add support for doxia macros in markdown documents.

- [MSITE-748](https://issues.apache.org/jira/browse/MSITE-748) EmptyStackException on xdoc toc macro usage

0 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Alex O'Ree](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=spyhunter99)** commented

Sorry I forgot to reply,  the failure for me was jumping from h4 to h2 and vice versa without a h3 in the middle.  I've only tested with markdown

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

ok, I found a failing case:

```
# Section level 1

<!-- MACRO{toc|fromDepth=1|toDepth=3} -->

   1. level 2

#### direct level 4

   1. level 2 
```

I'll investigate, since I fear it will happen that people write such valid Markdown code...
