### ISSUE TITLE
[DOXIA-91] Update Doxia Decoration model to actually work in reactor build.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia#649]
**[Henning Schmiedehausen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henning)** opened **[DOXIA-91](https://issues.apache.org/jira/browse/DOXIA-91?redirect=false)** and commented

This is a major patch to the decoration model to bring some sanity in the link resolution when it is used under the reactor build. It generates breadcrumbs and item links correctly in all scenarios that I have tested (the current HEAD code does not) and passes all the unit tests that are already there.

---

**Attachments:**
- [doxia-decoration.patch](https://issues.apache.org/jira/secure/attachment/12715504/doxia-decoration.patch) (_29.13 kB_)
- [doxia-decoration.patch](https://issues.apache.org/jira/secure/attachment/12715507/doxia-decoration.patch) (_16.10 kB_)
- [doxia-decoration-3.patch](https://issues.apache.org/jira/secure/attachment/12715468/doxia-decoration-3.patch) (_30.83 kB_)
- [doxia-decoration-4.patch](https://issues.apache.org/jira/secure/attachment/12715470/doxia-decoration-4.patch) (_51.36 kB_)
- [doxia-decoration-5.patch](https://issues.apache.org/jira/secure/attachment/12715471/doxia-decoration-5.patch) (_51.50 kB_)
- [org.apache.maven.doxia.site.decoration.inheritance.DecorationModelInheritenceAssemblerTest.txt](https://issues.apache.org/jira/secure/attachment/12715511/org.apache.maven.doxia.site.decoration.inheritance.DecorationModelInheritenceAssemblerTest.txt) (_26.28 kB_)

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I tried your latest patch and actual tests failed. Could you provide us test cases or review these? Tx.
Another way, as you know, we change license headers.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I forgot to say that I tried with maven 2.0.4 and 2.0.5

**Comment by jira-importer** [comment]
**[Henning Schmiedehausen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henning)** commented

Yep, same here. Maven 2.0.4 and 2.0.5-SNAPSHOT (do we have a release yet?).

Which platform did you use? I ran my tests on Linux, I don't have a built HEAD on Windows and the process of getting the jumble of maven, plexus, doxia and everything else to get built took my fastest machines two hours. I don't want to think how long my old windows notebook would take for this...

If you are on Windows, I will try to run the tests for you this weekend.

Can you attach the failed test report? That would help me tremendously.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Here is the surefire report.
I am on windows with 2.0.4 and 2.0.6-snapshot (trunk)
I tried with your latest patch:
http://jira.codehaus.org/secure/attachment/25052/doxia-decoration.patch

HTH

**Comment by jira-importer** [comment]
**[Henning Schmiedehausen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henning)** commented

Hm, that is a forward-slash / backward-slash issue. Will look into that.

**Comment by jira-importer** [comment]
**[Henning Schmiedehausen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henning)** commented

This version of the path passes all tests for me on Linux and Windows.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I got a NPE in a multi project case without any documentation.

```
java.lang.NullPointerException
        at java.io.File.<init>(File.java:194)
        at org.apache.maven.doxia.site.decoration.inheritance.PathUtils.getRelativeFilePath(PathUtils.java:130)
        at org.apache.maven.doxia.site.decoration.inheritance.PathUtils.getRelativePath(PathUtils.java:103)
        at org.apache.maven.doxia.site.decoration.inheritance.PathUtils.convertPath(PathUtils.java:40)
        at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.convertPath(DefaultDecorationModelInheritanceAssembler.java:338)
        at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.resolveBannerPaths(DefaultDecorationModelInheritanceAssembler.java:150)
        at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.resolvePaths(DefaultDecorationModelInheritanceAssembler.java:97)
        at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getDecorationModel(AbstractSiteRenderingMojo.java:555)
...
```
